### ISSUE TITLE
🛑 Test Dead Cloud Instance is down

### ISSUE THREAD

**Issue by shrkz1** [eramba/upptime#1]
In [`1e4e4a2`](https://github.com/eramba/upptime/commit/1e4e4a202817def0d54015a852fa6837987c6c60
), Test Dead Cloud Instance (https://dead.cloud.eramba.org) was **down**:
- HTTP code: 0
- Response time: 0 ms

**Comment by kisero** [comment]
this was some testing done when we installed this
