### ISSUE TITLE
🛑 Demo Enterprise Cloud API is down

### ISSUE THREAD

**Issue by shrkz1** [eramba/upptime#13]
In [`f1e7857`](https://github.com/eramba/upptime/commit/f1e785779e167f8c280732aebae0cd7b9b8aa7ac
), Demo Enterprise Cloud API (https://demo-e.cloud.eramba.org/api/projects/index) was **down**:
- HTTP code: 503
- Response time: 123 ms

**Comment by kisero** [comment]
https://eramba.cloud.eramba.org/security-incidents?advanced_filter=1&advanced_filter_id=1055&modalId=1&_page=1&id__show=1&title__comp_type=3&title=demo+saas+environments+down&title__show=1&description__comp_type=3&description=&description__show=1&type__comp_type=5&type__show=0&Classification-name__comp_type=5&Classification-name__show=0&Owner__comp_type=5&Owner__count=0&Owner__show=0&reporter__comp_type=3&reporter=&reporter__show=0&victim__comp_type=3&victim=&victim__show=0&open_date__comp_type=0&open_date=&open_date__use_calendar=1&open_date__show=1&closure_date__comp_type=0&closure_date=&closure_date__use_calendar=1&closure_date__show=1&security_incident_status_id__comp_type=0&security_incident_status_id=&security_incident_status_id__show=0&DynamicStatus_lifecycle_incomplete__comp_type=0&DynamicStatus_lifecycle_incomplete=&DynamicStatus_lifecycle_incomplete__show=0&AssetRisk__comp_type=5&AssetRisk__count=0&AssetRisk__show=1&AssetRisk-SecurityPolicyIncident__comp_type=5&AssetRisk-SecurityPolicyIncident__count=0&AssetRisk-SecurityPolicyIncident__show=1&ThirdPartyRisk__comp_type=5&ThirdPartyRisk__count=0&ThirdPartyRisk__show=1&ThirdPartyRisk-SecurityPolicyIncident__comp_type=5&ThirdPartyRisk-SecurityPolicyIncident__count=0&ThirdPartyRisk-SecurityPolicyIncident__show=1&BusinessContinuity__comp_type=5&BusinessContinuity__count=0&BusinessContinuity__show=1&BusinessContinuity-SecurityPolicyIncident__comp_type=5&BusinessContinuity-SecurityPolicyIncident__count=0&BusinessContinuity-SecurityPolicyIncident__show=1&SecurityService__comp_type=5&SecurityService__count=0&SecurityService__show=1&SecurityService-objective__comp_type=3&SecurityService-objective=&SecurityService-objective__show=0&Asset__comp_type=5&Asset__count=0&Asset__show=1&ThirdParty__comp_type=5&ThirdParty__count=0&ThirdParty__show=1&created__comp_type=0&created=&created__use_calendar=1&created__show=0&modified__comp_type=0&modified=&modified__use_calendar=1&modified__show=0&comment_message__comp_type=3&comment_message=&comment_message__count=0&comment_message__show=0&last_comment__comp_type=0&last_comment=&last_comment__use_calendar=1&last_comment__show=0&attachment_filename__comp_type=3&attachment_filename=&attachment_filename__count=0&attachment_filename__show=0&last_attachment__comp_type=0&last_attachment=&last_attachment__use_calendar=1&last_attachment__show=0&CustomField_11__comp_type=5&CustomField_11__show=0&id=&type=&Classification-name=&Owner=&AssetRisk=&AssetRisk-SecurityPolicyIncident=&ThirdPartyRisk=&ThirdPartyRisk-SecurityPolicyIncident=&BusinessContinuity=&BusinessContinuity-SecurityPolicyIncident=&SecurityService=&Asset=&ThirdParty=&CustomField_11=&_limit=-1&_order_column=created&_order_direction=DESC&_=1667807229999
