### ISSUE TITLE
🛑 Demo Community Cloud is down

### ISSUE THREAD

**Issue by shrkz1** [eramba/upptime#18]
In [`bc5321c`](https://github.com/eramba/upptime/commit/bc5321cec0729c229a3373bec125460222cb8b8b
), Demo Community Cloud (https://demo.cloud.eramba.org/login) was **down**:
- HTTP code: 503
- Response time: 500 ms

**Comment by kisero** [comment]
https://github.com/eramba/eramba/issues/3968
